### ISSUE TITLE
Weird ballistic values in arsenal

### ISSUE THREAD

**Issue by ImplicitDeny** [team-gsri/GSRI-Gear#10]
[-GSRI-] JPC Lead (OD) (JPC_3_OD) and [-GSRI-] JPC - Op 3 (OD) (JPC_1_OD) are displaying strange ballistic values in virtual arsenal. According to config values, both should be identical to any other GSRI vest, but arsenal is showing no ballistic protection.

**Comment by ImplicitDeny** [comment]
Weight values are totally non-consistent. Todo.

**Comment by ImplicitDeny** [comment]
After a few tests in VA, it looks like protection values are correctly used by damage calculation. However, correct values are still not displayed by VA.

**Comment by ArwynFr** [comment]
these vests will be deprecated soon : wontfix
