### ISSUE TITLE
Integrate GSRI's lockers into gear

### ISSUE THREAD

**Issue by ImplicitDeny** [team-gsri/GSRI-Gear#21]
Following https://github.com/team-gsri/GSRI-Opex/issues/74, reintegrate (and refactor, somehow ?) preslot functions and overall locker stuff here.

Also, add a hint when a player change its medical skills in order to let him know the change was made successfully.

**Comment by ArwynFr** [comment]
Also we don't use medical skill 1, only 0 or 2, maybe we can remove it ?
