### ISSUE TITLE
GL preslot doesn't have any GL ammo

### ISSUE THREAD

**Issue by Thibugs** [team-gsri/GSRI-Gear#56]

**Comment by Thibugs** [comment]
Those are the lines that should add the GL ammo to the slot 

https://github.com/team-gsri/GSRI-Gear/blob/9f491313448c003cac2c56cf081788863636d4d8/addons/gsri_props/lockers/Functions/fn_gearAsGcap.sqf#L130C2-L139

**Comment by ArwynFr** [comment]
Fixed #57
